### ISSUE TITLE
missing Notation.inc file ?

### ISSUE THREAD

**Issue by gmat** [modsim/FluxML#3]
Hi,
the compilation hits this : 
```
data/Notation.cc:1105:10: fatal error: Notation.inc: No such file or directory
 #include "Notation.inc"
```
There's no file named like this in the repository. Is it missing ? Or a fie to rename ?
Tks for your help,

**Comment by mbeyss** [comment]
Hi,

the `Notation.inc` file is auto generated by `re2c`. I would guess that you have `re2c` not installed or `configure` did not find it. If you look at the `config.log`file search for `checking for re2c`. Right now it is not appropriately checked if `re2c` is found. If you are running Ubuntu/Debian a `sudo apt-get install re2c` will fix this problem.

However I discovered a problem further down the process with `ExprParser.cc`. I will have a look at it and fix it asap

**Comment by mbeyss** [comment]
See issues #3 and #4
