### ISSUE TITLE
configure does not halt, if re2c is not present

### ISSUE THREAD

**Issue by mbeyss** [modsim/FluxML#4]
This will lead to confusing error messages later on about  missing files.

**Comment by csachs** [comment]
You can add the following line after https://github.com/modsim/FluxML/blob/ee5353f0cb2d59fbf1ae170d57e43a42efb1f47d/configure.ac#L82 .
```
AS_IF([test x"$RE2C" == x""], [AC_MSG_ERROR([Please install re2c first])])
```
